In [9]:
#Numpyをインポート
import numpy as np

#多次元行列のコードを記述
A=np.array([[0,1],[2,3],[4,5]])
B=np.array([[0,1,2,3],[4,5,6,7]])

#行列の積を計算して、結果を表示
print(np.dot(A, B))

#最大値を求める
print(np.dot(A, B).max())






[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
47
